# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ -f ~/.bash_profile ]; then
	. ~/.bash_profile
fi
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

# Fedora
alias reposearch="/bin/sudo /bin/repoquery -C --search"
alias reposearchinfo="/bin/sudo /bin/repoquery -C --info"
alias syncldir="rsync --progress -acpvvz"
alias pwgnr="cat /dev/urandom| tr -dc 'a-zA-Z0-9-_!@#$%^&*()_+{}|:<>?='|fold -w 12| head -n 1"
