# .bash_profile

# Get the aliases and functions
# if [ -f ~/.bashrc ]; then
# 	. ~/.bashrc
# fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin
PS1="\[$(tput bold)\]\[$(tput setaf 0)\][\t \d][\w]\n\[$(tput sgr0)\]\[$(tput bold)\]\[$(tput setaf 1)\]\u@\h \[$(tput sgr0)\]\[$(tput setaf 4)\]>> \[$(tput sgr0)\]\[$(tput sgr0)\]"

export PATH PS1
